services:
  db:
    image: postgres:16
    container_name: ts_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_sentiment
    ports:
      - "5432:5432"
    volumes:
      - ts_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twitter_sentiment"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: ts_api
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/twitter_sentiment
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app

volumes:
  ts_pgdata:
